### ISSUE TITLE
WProofreader is active in source mode highlighting HTML tags [CKEditor 4]

### ISSUE THREAD

**Issue by f1ames** [WebSpellChecker/wproofreader#1]
Hello WSC Team!
First of all, congratulations on launching WProofreader! 🎉 I spent some time using it when preparing CKEditor 4 documentation samples and it looks and works really nice and smooth. Keeping fingers crossed for its success 🤞

I found just few minor issue, will report them so you can consider some improvements.

---

## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://webspellchecker.com/wsc-proofreader/#proofreader-ckeditor4.
2. Create some complex content, for example:
```html
<h1>Broadcasting and <em>quotes</em> <a id="quotes" name="quotes"></a></h1>

<p>Broadcast on live TV to a world-wide audience, Armstrong stepped onto the lunar surface and described the event as:</p>

<blockquote>
<p>One small step for [a] man, one giant leap for mankind.</p>
</blockquote>

<p>Apollo 11 effectively ended the <a href="http://en.wikipedia.org/wiki/Space_Race">Space Race</a> and fulfilled a national goal proposed in 1961 by the late U.S. President <a href="http://en.wikipedia.org/wiki/John_F._Kennedy">John F. Kennedy</a> in a speech before the United States Congress:</p>

<blockquote>
<p>[...] before this decade is out, of landing a man on the Moon and returning him safely to the Earth.</p>
</blockquote>

```

3. Switch to source mode.

### Expected result

I would expect WProofreader to become inactive in source mode or just skip HTML tags (because it still correctly marks incorrect words there).

### Actual result

The WProofreader is active highlighting HTML tags:

![image](https://user-images.githubusercontent.com/1061942/62374375-23838d80-b53c-11e9-9a3c-65c7426050f0.png)

## Other details

Tested on Chrome with CKEditor 4 (may be also an issue for other editors with source mode).

**Comment by wsc-julia-shaptala** [comment]
@f1ames 

Thank you for such a detailed description of the problem and your suggestions.
Right now the fastest way for us will be just to disable WProofreader in the source mode for CKEditor 4 by default.

By the way, we do have a separate option `disableAutoSearchIn` which allows disabling WProofreader by class, id, data attribute name and HTML elements. Here is an example for CKEditor 4 source mode:

```
<script>
    window.WEBSPELLCHECKER_CONFIG = {
        ....
        disableAutoSearchIn: ['.cke_source']
        ....
    };
</script>
```

**Comment by wsc-julia-shaptala** [comment]
The fix has been released. Now WProofreader is disabled by default in the source mode of CKEditor.

**Comment by f1ames** [comment]
Hello @wsc-julia-shaptala, thanks for the quick fix 👍
