### ISSUE TITLE
[CKEditor 5] WProofreader balloon opens while dropdown is opened

### ISSUE THREAD

**Issue by Mgsy** [WebSpellChecker/wproofreader#12]
## Steps to reproduce
1. Insert some word with a typo at the beginning of the first block of the document.
2. Hover this word to open a balloon (don't move a mouse).
3. Press Alt + F10.
4. Press Enter.

## Current result
WProofreader balloon opens and covers a heading dropdown.

**Comment by wsc-julia-shaptala** [comment]
Yes, this is an issue. The expected behavior is to close our balloon (correction box) for all keypress events (including modifier keys).

Also, this issue is related to #8 and #10.

**Comment by wsc-julia-shaptala** [comment]
The fix has been released, now WProofreader balloon will be closed for all keypress events (including modifier keys).
