### ISSUE TITLE
[CKEditor 5] Correcting a word doesn't work in a table cell if it contains the user marker

### ISSUE THREAD

**Issue by Mgsy** [WebSpellChecker/wproofreader#15]
To reproduce this issue it's required to run the editor with real-time collaboration.

## Steps to reproduce
1. Insert a table.
2. Insert the word "tewst" to a table cell.
3. On Client A put the caret in this word.
4. Try to correct the word on Client B.

## Current result
It's impossible to correct the word.

**Comment by wsc-julia-shaptala** [comment]
@Mgsy, 
@jalners will investigate this issue and get back with the next steps.

**Comment by wsc-julia-shaptala** [comment]
We've rechecked this issue after adding CKE5's API: `editor.execute( 'input', { text: 'hello' } )` and this is not longer reproducible.

@Mgsy, please confirm if the issue is solved.

**Comment by Mgsy** [comment]
>@Mgsy, please confirm if the issue is solved.

This issue is fixed, thanks.

**Comment by wsc-julia-shaptala** [comment]
Great, thank you for the confirmation.
