### ISSUE TITLE
No need for a workaround to assign the editor instance to a HTMLElement

### ISSUE THREAD

**Issue by mlewand** [WebSpellChecker/wproofreader#17]
Currently the [Configuring WProofreader Cloud for CKEditor 5 v12.0+](https://docs.webspellchecker.net/pages/viewpage.action?pageId=453345304) have following listing:

```
ClassicEditor.create(
	document.querySelector('#editor')
).then((editor) => {
	editor.ui.getEditableElement('main').editor = editor;
});
```

Given that [CKEditor 5 now adds `ckeditorInstance` property](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#how-to-get-the-editor-instance-object-from-the-dom-element) there's no need for this workaround anymore.

**Comment by wsc-julia-shaptala** [comment]
@mlewand,
This workaround is still required for the correct work with the `Proofread in dialog` mode. However, we do plan to replace the previous workaround with the `ckeditorInstance` property.  This is already scheduled for the next upcoming release by the end of August.

As soon as this flow is implemented and released, we will update the docs.

**Comment by wsc-julia-shaptala** [comment]
With today's release we start using the `ckeditorInstance` property. Thus, for CKEditor 5 v12.3.0 or higher, this workaround is not longer needed. Our [guides](https://docs.webspellchecker.net/pages/viewpage.action?pageId=453345304) are updated accordingly.
