### ISSUE TITLE
Issues with keyboard navigation

### ISSUE THREAD

**Issue by Comandeer** [WebSpellChecker/wproofreader#18]
There are some issues with the keyboard navigation (checked on [CKEditor 4 demo](https://webspellchecker.com/wsc-proofreader/#proofreader-ckeditor4)):

* WProofreader button is focusable, but it is added as the last focusable element on the page. It should be added as the next focusable element after the editor itself.
* After opening the dialog, all buttons inside it don't react to pressing <kbd>Space</kbd> key.

**Comment by wsc-julia-shaptala** [comment]
1. Yes, we do confirm the issue with the WProofreader badge. This issue will be fixed as a part of the upcoming release.
2. [Here](https://docs.webspellchecker.net/display/KnowledgeBase/WProofreader+Keyboard+Navigation) is a detailed overview of the supported keyboard navigation.

**Comment by Comandeer** [comment]
> Here is a detailed overview of the supported keyboard navigation.

TBH I find these docs hard to understand, as everything is presented in the form of images. It would be better (and more accessible) to accompany these images with some text.

Despite that fact, buttons (menu, maximise, close, accept; basically all elements with `[role=button]`) should react to pressing <kbd>Space</kbd>, to mimic the behaviour of native `button` elements. In fact many screen readers announce buttons adding a suggestion to press them using <kbd>Space</kbd> key.

**Comment by wsc-julia-shaptala** [comment]
Yes, your are right regarding the navigation using <kbd>Space</kbd>. The element which is used for the buttons natively reacts on <kbd>Enter</kbd> pressing. Nevertheless, we will consider adding this later.

As to the documentation, this will be improved in the nearest time. Thanks for sharing your recommendations.

**Comment by wsc-julia-shaptala** [comment]
@Comandeer 

> WProofreader button is focusable, but it is added as the last focusable element on the page. It should be added as the next focusable element after the editor itself.

Just to let you know that the fix for issue has been released today.

**Comment by wsc-julia-shaptala** [comment]
In about a week, we plan to release the update that provides improvement keyboard navigation.

**Comment by jshaptala** [comment]
@Comandeer, just a short status update. Last week, on Nov 14, we released the minor release that includes the improvement with the keyboard navigation and added <kbd>Space</kbd> key.
