### ISSUE TITLE
Wproofreader require unsafe-inline and unsafe-eval to work (CSP)

### ISSUE THREAD

**Issue by mlewand** [WebSpellChecker/wproofreader#19]
It would be great if Wproofreader didn't require `'unsafe-inline' 'unsafe-eval'` content security policy settings.

Without above settings you get following errors:

* No `unsafe-eval`:
	```
	wscbundle.js:38 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://svc.webspellchecker.net".

		at new Function (<anonymous>)
		at f (wscbundle.js:38)
		at f (wscbundle.js:38)
		at Object.render (wscbundle.js:38)
		at b.value [as _original_render] (wscbundle.js:42)
		at b.render (wscbundle.js:43)
		at Object.render (wscbundle.js:45)
		at d.buildElement (wscbundle.js:45)
		at d.init (wscbundle.js:45)
		at wscbundle.js:36
	```
* no `unsafe-inline`:
	```
	Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https://svc.webspellchecker.net". Either the 'unsafe-inline' keyword, a hash ('sha256-4YQgZ2iWooOAGOb+ToWyEAxGEEWI3YiEPXDjCdzRx6Q='), or a nonce ('nonce-...') is required to enable inline execution.
	```

**Comment by mlewand** [comment]
Your solution for `unsafe-inline` works like a charm. So the only thing open is the `unsafe-eval` policy 🤞

**Comment by jalners** [comment]
Thank you for confirming that our recommendations for `unsafe-inline` worked for you well.

And we have good news for you regarding `unsafe-eval`. Yesterday, we conducted a small investigation and it appeared that the fix will not take a lot as we thought initially. It would take us an additional time for testing but we expect it will be live soon (approximately mid of October).

**Comment by mlewand** [comment]
Great news! I'll keep an eye on the issue. I'm sure this will allow more people/companies to use Wproofreader.

**Comment by jshaptala** [comment]
@mlewand the fix for this issue was released last week, on Nov 14, 2019.
Could you please recheck if you are not having issues with **content security policy** when using WProofreader?

**Comment by jshaptala** [comment]
@mlewand Did you have to take a look and check our fix?

**Comment by mlewand** [comment]
Hey @jshaptala @jalners I can confirm that `unsafe-eval` is no longer required, thanks!
