### ISSUE TITLE
[CKEditor 5] WProofreader doesn't work with editor collaboration features

### ISSUE THREAD

**Issue by jswiderski** [WebSpellChecker/wproofreader#22]
When using WProofreader together with CKEditor 5 Collaboration, the https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-realtimecollaborationclient-editor-setdata-and-editor-data-set-are-forbidden-in-real-time-collaboration error is thrown after correcting spelling mistakes.

This is because WProofreader is most likely using `setData` method should not be used with Real Time Collaboration. Please see: https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/real-time-collaboration/real-time-collaboration-integration.html#data-initialization

**Comment by jshaptala** [comment]
@jswiderski thanks for reporting this one. That's partially true. The issue only appears when using the `Proofread in dialog` mode and **not** in the `Proofread as you type` mode. The mentioned issue in the dialog was discussed a bunch of times, you can find the detailed explanation in the open issue #11.

Our recommendation for all customers who are interested in use of the collaborative mode is to disable the `dialog` at all and keep only `as you type` mode.

There is an API option for WProofreader that allows easily to disable the `Proofread in dialog` mode.

```
window.WEBSPELLCHECKER_CONFIG = {
    ....
    actionItems: ['addWord', 'ignoreAll', 'settings', 'toggle']
};
```

**Comment by jshaptala** [comment]
UPD. In the plugin for CKEditor 5, we've disabled `Proofread in dialog` mode by default.
