### ISSUE TITLE
Can not type Enter Key on Firefox

### ISSUE THREAD

**Issue by nguyenvannhan** [WebSpellChecker/wproofreader#23]
Hello everyone,
I'm using the trial of WProofreader with Textarea tag.
When I test on Google Chrome, Everything's OK.
But when I run on Firefox, I can not use enter key.
And when I copy, all enter character change to space character.
Please help me check and how I can resolve it.
Thanks very much.

**Comment by jshaptala** [comment]
Hi @nguyenvannhan, please accept our apologies for the delayed reaction to this request. We haven't experienced the mentioned problem before. Would you please create a sample demo for us or a sample page where we can reproduce the mentioned behavior?

**Comment by jshaptala** [comment]
Hi @nguyenvannhan! Is the issue current for you? Would you please provide additional details, like a demo?

**Comment by jshaptala** [comment]
Since there are no additional details provided, we are not able to confirm the issue.
