### ISSUE TITLE
Add tooltip to count badge 

### ISSUE THREAD

**Issue by begandroide** [WebSpellChecker/wproofreader#26]
Hi! Im trying to add some tooltip to count badge and i can't resolve it reading the docs, you know if this is possible?

I only want inject a tooltip on badge for user entendability.

**Comment by jshaptala** [comment]
Hi @begandroide,

Right now there is no such an option to add a tooltip externally. It should be added on our side.

Do you want to add something like `Problems found: 2`?

Thanks,

**Comment by begandroide** [comment]
Hi @jshaptala thanks for the quick response, yes i want to add a traducible badge exactly how you mencioned.

Thanks you!

**Comment by jshaptala** [comment]
We will be happy to add this improvement in the next release of WProofreader that is planned for the end of January. We already have a relatively large scope for changes in WProofreader and it will be time-efficient to add this minor change to that scope. Once it is live, I will be happy to let you know.

**Comment by begandroide** [comment]
Thank you for considering the enhancement, we will hope the next release 🥳

**Comment by jshaptala** [comment]
Hi @begandroide, Just wanted to let you know that the tooltip count has been added to the badge. Now it says `Problems found: X`. However, please note that we do plan to change text a bit with the next small release to `Suggestions found: X`.

**Comment by begandroide** [comment]
Hi @jshaptala thanks for the feature! I can see this change on my app, but i has a question, the tooltip is translatable?

**Comment by jshaptala** [comment]
Yes, of course. We do plan to release localizations for the UI to the most popular languages. By the way, what languages are required for your app?

**Comment by begandroide** [comment]
Perfect, my app use English and Spanish, but in the future we plain to use more languages.

**Comment by jshaptala** [comment]
Ok, got it.
