### ISSUE TITLE
set Ignore All Caps Words in ckeditor config

### ISSUE THREAD

**Issue by EngMustafaTaha** [WebSpellChecker/wproofreader#28]
I need to set ignoreAllCapsWords to true in ckeditor config so when the user open the settings dialog he will set it set to true

**Comment by jshaptala** [comment]
Hi @EngMustafaTaha,

If you are using WProofreader, please refer to API options doc here: https://webspellchecker.com/docs/api/wscbundle/Options.html

The following option should be added to `WEBSPELLCHECKER_CONFIG` not to CKEditor config.js file.

```<script>
    window.WEBSPELLCHECKER_CONFIG = {
        ...
        ignoreAllCapsWords: true,
        ...
   };
</script>```

Hope that helps.

**Comment by jshaptala** [comment]
Hi @EngMustafaTaha, is your question still actual or did my answer help?

**Comment by EngMustafaTaha** [comment]
> Hi @EngMustafaTaha, is your question still actual or did my answer help?

Yeah, It worked. Thank you for your help and sorry because I forgot to replay to you.

**Comment by jshaptala** [comment]
@EngMustafaTaha OK, that's good to hear. Thanks for letting me know.
