### ISSUE TITLE
WProofreader panel covers CKEditor context menu [CKEditor 4]

### ISSUE THREAD

**Issue by f1ames** [WebSpellChecker/wproofreader#3]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://webspellchecker.com/wsc-proofreader/#proofreader-ckeditor4.
2. Right-click on highlighted word.

### Expected result

It should be possible to use context menu before WProofreader panel opens.

### Actual result

CKEditor 4 context menu is opened and WProofreader opens over context menu.

![wpr 2](https://user-images.githubusercontent.com/1061942/62378418-1323e080-b545-11e9-807e-6ce22ef2ed3e.gif)

## Other details

Tested on Chrome with CKEditor 4. From what I see the WProofreader panel appears on hover so it's enough to move mouse cursor away and then the panel gets hidden and one may use context menu. So it's really a minor issue.

**Comment by wsc-julia-shaptala** [comment]
This is an expected behavior for WProofreader in all rich text editors as the `z-index` value is higher.   
If this is an issue, we suggest using classic SCAYT plugin for CKEditor 4.

**Comment by f1ames** [comment]
> This is an expected behavior for WProofreader in all rich text editors as the `z-index` value is higher.
If this is an issue, we suggest using classic SCAYT plugin for CKEditor 4.

Makes sense 👍

**Comment by wsc-julia-shaptala** [comment]
Thanks for confirmation.
