### ISSUE TITLE
Theme option is NOOP (sticks to Orange theme)

### ISSUE THREAD

**Issue by vitality82** [WebSpellChecker/wproofreader#30]
I've integrated including the script and specified the theme prop (as mentioned in the documentation):

`<script src="https://svc.webspellchecker.net/spellcheck31/wscbundle/wscbundle.js" type="text/javascript"></script>`

Tried:

`window.WEBSPELLCHECKER.init({ container: element, theme: "gray" })`

and

`
var WSC_SERVICE_ID = [MY_SERVICE_ID]
window.WEBSPELLCHECKER_CONFIG = {
		"serviceId": WSC_SERVICE_ID,
		"autoSearch": true,
		"autoDestroy": true,
		"disableBadgePulsing": true,
		"theme": 'gray'
	}
`

No theme is applied to textarea, ckeditor or input fields. Do I need to include a separate CSS file?

**Comment by AAbakumov** [comment]
Hello @vitality82. The specified 'theme' value affects only WProofreader elements (dialog, hover etc. ) and it can't override textarea's or ckeditor's styles. Could you please explain your expected result in a more detailed way, like providing a screenshoot for us with marked elements you expected to be overwritten. 

Also, you can play with different themes on our public demos to see how it works:
https://demos.webspellchecker.com/wproofreader-html-controls.html

For example, our badge button always stays orange. This is expected.

**Comment by vitality82** [comment]
I went to re-brand the orange badge - based on the styling suggestions:

[https://docs.webspellchecker.net/pages/viewpage.action?pageId=468844969](https://docs.webspellchecker.net/pages/viewpage.action?pageId=468844969)

> Examples of current styles for main UI elements
Below are examples of current CSS styles for UI elements that you might want to overwrite with your custom styles.

Spinner inside badge

**Comment by AAbakumov** [comment]
@vitality82 Does it work fine for you?

**Comment by vitality82** [comment]
No, the problem is the spinner. The syles (orange theme) are imported via the wscbundle script and the spinner is located at svg/spinner.svg. I've tried to re-color it but then I loose the animations. I've uncrompressed the css styles from this repo and there's more to it (gif alternative for older browsers). The temes (gray, dark..etc) do not override the badge - which is why I'm questioning above why there even is documentation that explains how to override the badge styles.

I'm keeping it orange for now, unless more flexibility is provided?

**Comment by nadya-bodrova** [comment]
Dear @vitality82, 

If you need to change the spinner to your own, then you can do it like this:

```
.wsc-theme-gray.wsc-badge--checking .wsc-badge__label-button {
    background-image: url(path/to/you/spinner) !important;
}
```

Please note that you can also hide the WProofreader badge at all if needed, and move the part of action items, specifically Settings, Disable/Enable and Proofread in dialog from the badge area to the suggestions pop-up: 

`enableBadgeButton: false.`

**Comment by vitality82** [comment]
Thanks, and regarding hiding or showing the badge, is there a method exposed to do this dynamically?

**Comment by vitality82** [comment]
To answer my own question: Yes via the `commitOption` api.

**Comment by AAbakumov** [comment]
@vitality82 We are happy to hear that you have found the way to resolve this case!
