### ISSUE TITLE
[CKEditor5] Make WProofreader work with Restricted Editing mode 

### ISSUE THREAD

**Issue by jswiderski** [WebSpellChecker/wproofreader#31]
In Restricted editing mode typing in only possible in dedicated areas - https://ckeditor.com/docs/ckeditor5/latest/features/restricted-editing.html 

WProofreader should only check spelling and allow correcting it in those dedicated areas.

At the moment WProofreader underlines mistakes in whole text. What is more, it allows opening context menu but selecting any option from that menu has no effect which can be misleading for users.

**Comment by jshaptala** [comment]
As a temporary solution, we will **disable** WProofreader by default in the restricted editing mode in CKEditor 5.

**Comment by jalners** [comment]
Hi @jswiderski,

We have added `disabling/enabling` functionality for the WProofreader when the following modes are `on/off`: "Restricted editing", "Source editing", "Read-only", "Comments-only".
This fix is already in our npm package version 2.1.0.

**Comment by jalners** [comment]
Hi @jswiderski,

We have added correct support for the `CKEditor5 Restricted editing`.
It is already in our npm package version `2.2.0`.
