### ISSUE TITLE
[CKEditor 5] Accessibility concerns related to WProofreader badge element

### ISSUE THREAD

**Issue by jswiderski** [WebSpellChecker/wproofreader#32]
According to Access Assistant Chrome plugin as well as https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls, this attribute should identify the element (or elements) whose contents or presence are controlled by the element on which this attribute is set. The badge contains `aria-controls="wsc-badge_wsc_7_680689105` but there is no element with such an id.

According to https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded, the `aria-expanded` attribute is set on an element to indicate if a control is expanded or collapsed, and whether or not its child elements are displayed or hidden. This attribute should not be used on the badge as it does not expand.

**Comment by jshaptala** [comment]
The issue was fixed in v5.24.0 (https://webspellchecker.com/release-notes/v5-24-0/), August 2022.
