### ISSUE TITLE
WProofreader badge is it every possible to configure the orange dots floating or upper left corner?

### ISSUE THREAD

**Issue by 7seven7lst** [WebSpellChecker/wproofreader#33]
is it every possible to configure the orange dots floating or display at upper left corner instead?

right now it's set to display at lower right corner of the doc.

**Comment by 7seven7lst** [comment]
hi @jshaptala thanks for the quick reply. The use case we have is:
we have a very long essay that user will need to scroll all the way to the bottom to see the orange dot. If we have it at the top left corner or floating, it will be much more convenient. 

Although technically it's possible to set the width and overflow scroll, we cannot do it convenient in this case because we have some customized highlighting and scroll that we will need to do which would not function well if we set a fixed width and overflow scroll

**Comment by jshaptala** [comment]
@7seven7lst thank you a lot for providing more details about your use case. It does make perfect sense to me and why you look for more options to customize the default position of the badge. And I'm happy to let you know that we've made some progress on this one and are about to introduce a “global badge” state that would allow developers to set XY and z-index positions of the badge on the page. ETA is the end of this week.

**Comment by jshaptala** [comment]
@7seven7lst I'm happy to inform you that yesterday we released an updated version of the global badge state.

By default, it’s disabled `globalBadge:false` but if enabled it will be placed in the bottom right corner of the page. Its position can be regulated using the following options: `badgeOffsetX`, `badgeOffsetY`, `badgeOffsetZ` (by default: `badgeOffsetX = 20`, `badgeOffsetY = 20`, `badgeZIndex=1000`).  

Please get back to us via [support@webspellchecker.net](mailto:support@webspellchecker.net) with feedback or additional questions.

**Comment by 7seven7lst** [comment]
@jshaptala this is awesome thanks.

**Comment by jshaptala** [comment]
FYI information that was an error with the parameter name in my previous message. It was `badgeOffsetZ` but should have been `badgeZIndex`.
