### ISSUE TITLE
Incorrect word in nested editables is not highlighted in WProofreader dialog [CKEditor 4]

### ISSUE THREAD

**Issue by f1ames** [WebSpellChecker/wproofreader#4]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://codepen.io/f1ames/pen/jgGNxM.
2. Add `serviceId` in the config to activate WProofreader.
3. Focus editor.
4. Open `Proofread in dialog`.

### Expected result

The same words are highlighted as incorrect in the editor and Proofread dialog.

### Actual result

Some words are not highlighted as incorrect in the Proofread dialog.

_Editor content_:
![image](https://user-images.githubusercontent.com/1061942/62379725-d4435a00-b547-11e9-9060-3380a00b90d7.png)

_Dialog content_:
![image](https://user-images.githubusercontent.com/1061942/62379779-e8875700-b547-11e9-8671-ab88a5502980.png)

## Other details

Tested on Chrome with CKEditor 4 (`4.12.1`). Also on the second screenshot you can see strange pattern under the image - it is a drag handler which got broken due to lack of CSS.

**Comment by wsc-julia-shaptala** [comment]
This one is directly related to #11. Please take a look at answer there and provide your comments.

**Comment by f1ames** [comment]
This is the same case as described in #11 - `contenteditable="false"` > `contenteditable="true"` nesting. Since @Reinmar already covered it in details in https://github.com/WebSpellChecker/wproofreader/issues/11#issuecomment-521132408 I don't have any more insightful feedback.

I was thinking of closing this as a duplicate of #11, however I'm not sure if solution for #11 will also fix this issue in CKEditor 4 so leaving it open for now.

**Comment by wsc-julia-shaptala** [comment]
Yes, unlike CKEditor 5, for CKEditor 4 this issue will be still present. Since there are plugins for CKEditor are available, we won't be fixing this issue.
