### ISSUE TITLE
[CKEditor 5] "Finish checking" button makes the editor crash after changing the selection

### ISSUE THREAD

**Issue by Mgsy** [WebSpellChecker/wproofreader#6]
## Steps to reproduce
1. Open `Proofread in dialog`.
2. Click on the `Finish checking` button.
3. Put the selection in the editor.

## Current result
The editor crashes.

## Error
```
utils.js:37 Uncaught TypeError: Cannot read property 'is' of undefined
    at isWidget (utils.js:37)
    at Widget._onMousedown (widget.js:137)
    at Document.<anonymous> (widget.js:91)
    at Document.fire (emittermixin.js:207)
    at MouseObserver.fire (domeventobserver.js:96)
    at MouseObserver.onDomEvent (mouseobserver.js:28)
    at ProxyEmitter.listenTo.useCapture (domeventobserver.js:79)
    at ProxyEmitter.fire (emittermixin.js:207)
    at HTMLDivElement.domListener (emittermixin.js:235)
```

**Comment by wsc-julia-shaptala** [comment]
We will double-check this issue. However, it seems that you didn't provide access to CKEditor 5 instance through DOM element as it is described in our [Docs (Step 3)](https://docs.webspellchecker.net/pages/viewpage.action?pageId=453345304).

```
<textarea name="content" id="editor">This is a sample text.</textarea>
  
<script>
    ClassicEditor.create(
        document.querySelector('#editor')
    ).then((editor) => {
        editor.ui.getEditableElement('main').editor = editor;
    });
</script> 
```

@Mgsy, could you please recheck if the issue persistent after adding this code?

**Comment by Mgsy** [comment]
>@Mgsy, could you please recheck if the issue persistent after adding this code?

Thanks, @wsc-julia-shaptala, you're right. I didn't attach this line to my code. Now it works like a charm, so I consider this issue invalid.

**Comment by wsc-julia-shaptala** [comment]
Great, thank you for the confirmation!
