### ISSUE TITLE
[CKEditor 5] Crash after correcting a word

### ISSUE THREAD

**Issue by Mgsy** [WebSpellChecker/wproofreader#7]
## Steps to reproduce
1. Set the following data: `editor.setData( '<p>Pugnant Stoici cum Peripateticis.</p>' )`.
2. Make the following selection: `Pugnant Stoici c[um Peri]pateticis.`.
3. Press Ctrl + B.
4. Hover word "Peripateticis".
5. Correct it.

## Current result
The editor crashes.

## Error
```
mapper.js:358 Uncaught TypeError: Cannot read property 'parent' of null
    at Mapper.findMappedViewAncestor (mapper.js:358)
    at Mapper.on.priority (mapper.js:97)
    at Mapper.fire (emittermixin.js:207)
    at Mapper.toModelPosition (mapper.js:258)
    at MutationHandler._handleTextMutation (injecttypingmutationshandling.js:221)
    at MutationHandler.handle (injecttypingmutationshandling.js:68)
    at Document.<anonymous> (injecttypingmutationshandling.js:22)
    at Document.fire (emittermixin.js:207)
    at MutationObserver._onMutations (mutationobserver.js:247)
```

**Comment by Reinmar** [comment]
I think that we should fix it on our side. I opened a ticket: https://github.com/ckeditor/ckeditor5-typing/issues/216 and we'll try to squeeze it in the current iteration.

**Comment by Reinmar** [comment]
Unfortunately, we won't able to handle this scenario on our side in the near future. 

I think that there may be a workaround, though – if you can trigger deletion of the text first and then insert the new text, that will prevent issues, I think.

I tested:

```
document.execCommand('delete');
document.execCommand('insertText', false, 'hello');
```

and it worked fine. At least, in this case.

**Comment by wsc-julia-shaptala** [comment]
As discussed we will try to use CKE5's API: `editor.execute( 'input', { text: 'hello' } )` as a temporary solution until you will fix the problem on your end.

**Comment by wsc-julia-shaptala** [comment]
The fix for the issue has been released. We used CKE5's API: editor.execute( 'input', { text: 'hello' } ) as a temporary solution.
@Mgsy, please confirm if the issue is solved.

**Comment by Mgsy** [comment]
>@Mgsy, please confirm if the issue is solved.

I can confirm that this issue is fixed.

**Comment by wsc-julia-shaptala** [comment]
@Mgsy, thanks for the confirmation. I'm closing this one then.
