### ISSUE TITLE
[CKEditor 5] Word correction doesn't work after list item indentation

### ISSUE THREAD

**Issue by Mgsy** [WebSpellChecker/wproofreader#8]
## Steps to reproduce
1. Create two list items.
2. Insert some word with a typo to the second list item.
3. Hover this word, put the selection inside of it and wait for a WProofreader balloon.
4. Press TAB.
5. Correct a word with some of the proposed words.

## Current result
Nothing happens.

## Expected result
A word has been corrected.

**Comment by wsc-julia-shaptala** [comment]
Actually this problem is related to #12. The expected behavior is to close our balloon for all keypress events (including TAB). Thus, once you press TAB, a WProofreader balloon will be closed.

**Comment by wsc-julia-shaptala** [comment]
The fix has been released, now WProofreader balloon will be closed for all keypress events (including modifier keys).
